name: Doc

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Generate document
      run: |
        npm ci
        npm run build:doc
    - name: GitHub Pages Deploy
      uses: maxheld83/ghpages@v0.2.1
